MPMP-34: Removed develop from pipelines, added missing lint-baseline files

diff --git a/config/git/hooks/pre-commit b/config/git/hooks/pre-commit
--- a/config/git/hooks/pre-commit
+++ b/config/git/hooks/pre-commit
@@ -13,3 +13,18 @@ if [ $EXIT_CODE -ne 0 ]; then
   exit $EXIT_CODE
 fi
 rm $OUTPUT
+
+echo "Running lint check..."
+LINT_OUTPUT="/tmp/lint-$(date +%s)"
+./gradlew lint > "$LINT_OUTPUT"
+LINT_EXIT_CODE=$?
+if [ $LINT_EXIT_CODE -ne 0 ]; then
+  cat "$LINT_OUTPUT"
+  rm "$LINT_OUTPUT"
+  echo "***********************************************"
+  echo "                  lint failed                  "
+  echo " Please fix the above issues before committing "
+  echo "***********************************************"
+  exit $LINT_EXIT_CODE
+fi
+rm "$LINT_OUTPUT"
